name: Build Kernel

on:
  push:
  workflow_dispatch:
env: 
  CI: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v10
      with:
        swap-size-mb: 32768

    - name: Build Kernel
      run: |
        wget -q 'https://drive.usercontent.google.com/download?id=1NNeoUX6T4UMeodwbhA02teTFyzuUmNlO&export=download&confirm=t' -O toolchain.tar.gz
        tar -xf toolchain.tar.gz
        git clone --depth 1 https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-installer.git
        cd kali-nethunter-installer
        git clone --depth 1 https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-kernels kernels
        python build.py --help
